# Generated by Django 5.2.3 on 2025-06-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_compleated',
            new_name='is_completed',
        ),
    ]
